### ISSUE TITLE
Pass indexes of ancestors to visitor

### ISSUE THREAD

**Issue by radarfox** [syntax-tree/unist-util-visit-parents#13]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

In the visitor function only nodes of ancestors are available. Can indexes of ancestors in their sibling arrays (`parent.children`) be added? Or at least the index for the current node, [which should be already available when calling the visitor function](https://github.com/syntax-tree/unist-util-visit-parents/blob/58e20d8366363b8b6e22d2e9c82d2ded408ecf16/lib/index.js#L344)?

I'm worried about performance when obtaining this `index` in the visitor function, as you need to do `parent.children.indexOf(node)` ([as `unist-util-visit` does](https://github.com/syntax-tree/unist-util-visit/blob/bc59f3bb488a71a1aab3da094306022eeecabda8/lib/index.js#L310C28-L310C57)), which is making the time complexity worse. The algorithm is walking not only all the nodes of tree, but it also needs to walk all sibling nodes for the every node in tree.

### Solution

`result = toResult(visitor(node, parents, index))`

https://github.com/syntax-tree/unist-util-visit-parents/blob/58e20d8366363b8b6e22d2e9c82d2ded408ecf16/lib/index.js#L346

### Alternatives

Loose performance doing `parent.children.indexOf(node)`

**Comment by wooorm** [comment]
This complicates the API.
I think the alternative is fine.
The theoretical performance win is likely small compared to other things done when traversing and transforming trees.
Perhaps you can expand more on your performance problems, so we can help with them?

**Comment by radarfox** [comment]
The performance seems to be affected a lot for large trees. I'm using the following test:

```typescript
import { Root } from 'hast';
import { visit } from 'unist-util-visit';
import { visitParents } from 'unist-util-visit-parents';

const tree: Root = {
  type: 'root',
  children: Array.from({ length: 10_000 }).map((value, index) => ({
    type: 'text',
    value: String(index),
  })),
};
let result;
console.time('visit');
visit(tree, (node) => {
  result = node.type;
});
console.timeEnd('visit');
console.time('visitParents');
visitParents(tree, (node) => {
  result = node.type;
});
console.timeEnd('visitParents');
console.log(result);
```

Output of console on my machine:

```
visit: 14.921875 ms
visitParents: 6.9228515625 ms
```

So, just for 10 000 nodes, not using the `indexOf` function, walks all nodes twice as fast.

For 100 000 nodes the performance is more than 10 times better:

```
visit: 715.27099609375 ms
visitParents: 53.43603515625 ms
```

This project seemed to me as one of core Unified.js utilities (2 000+ dependents). I believe this could have noticeable positive impact for many users of this library, including me. It shouldn't be hard to implement, as `unist-util-visit-parents` should already know these indexes, to effectively walk the tree. It should be just about passing them to the visitor function.

**Comment by wooorm** [comment]
Your conclusion (not using the indexOf function, walks all nodes twice as fast) is incorrect? There are different things `unist-util-visit` does? If you actually wanted to test what you say is tested, you need to modify visitParents to also pass an index to `visit`, and compare the two `visit`s: with or without `.indexOf`

---

This is a completely theoretical example: if you have 100k nodes next to each other, every other process is terribly slow already, your whole Node is crashing

---

> I believe this could have noticeable positive impact for many users of this library, including me.

Then you need to explain how this would improve your use case, what performance problems you are running into, and how this practically improves your performance.

> It shouldn't be hard to implement

It isn’t about how hard or easy it is to add more code. It is about whether that code is useful.

**Comment by wooorm** [comment]
You also propose to add a new array, that gets pushed and popped from. That will also take time to calculate

**Comment by wooorm** [comment]
I’m open to discussing this again with a practical benchmark of what is being proposed. A real test, with a lot of nodes, with both behaviors.

> I believe this could have noticeable positive impact for many users of this library, including me

Particularly this, I’d like to hear about the exact case you have, and how much it helps there.

Thanks!
