### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: name

### ISSUE THREAD

**Issue by speed4** [syntax-tree/unist-util-visit-parents#14]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

5.1.3

### Steps to reproduce

Use chrome 42 to open the web page containing unist-util-visit-parents@5.1.3

"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2309.0 Safari/537.36"

### Expected behavior

The console does not report any errors

### Actual behavior

Uncaught TypeError: Cannot redefine property: name

Object.defineProperty(visit, 'name', {
        value: 'node (' + color(node.type + (name ? '<' + name + '>' : '')) + ')'
      });

### Affected runtime and version

node@14.20.0

### Affected package manager and version

npm@6.14.17

### Build and bundle tools

webpack

**Comment by ChristianMurphy** [comment]
Welcome @speed4! 👋 
Sorry you ran into a spot of trouble.

The `syntax-tree` packages are designed to run on Node.js 16+.
It can also be compiled to target the web, for a web target it should work on recent versions of evergreen browsers.

Chrome 42 is over 8 years old now, and hasn't been supported in years.
My suggestion would be upgrade your Chrome version, it is **_very insecure_**.

If you still want to try to make things compatible with unsupported browsers.
You are welcome to try out various transpilers like babel and swc, and polyfills like core.js.

Understand that Chrome 42 isn't a target/supported platform of `unist-util-parents`, so this isn't a bug.
