### ISSUE TITLE
Unexpected behavior when replacing visited node

### ISSUE THREAD

**Issue by inklesspen** [syntax-tree/unist-util-visit-parents#5]
I'm processing some invalid HTML (produced by Google Docs) in HAST format. It has a couple of weird quirks; the root element is a `<b>` tag and `<hr>` tags are enclosed in `<p>` tags.

Example of invalid HTML:

```html
<b style="font-weight:normal;" id="docs-internal-guid-854aeed3-7fff-b376-ec26-0b76e18b46f3">
    <p><span>Lorem ipsum</span><span><br /></span><span><br /></span><hr /></p>
    <p><span>Lorem ipsum</span></p>
</b>
```

In order to fix this, I'm using `unist-util-visit`. I'm opening the issue here because that package is just a simple wrapper around this one.

My visitor looks like this:

```js
import utilIs from 'unist-util-is';
import isElement from 'hast-util-is-element';
import utilVisit from 'unist-util-visit';
import hastscript from 'hastscript';

utilVisit(hast, (node, index, parent) => {
  if (isElement(node, 'b') && utilIs('root', parent)) {
    parent.children.splice(index, 1, hastscript('div', node.children));
    return index;
  }
  if (isElement(node, 'p') && node.children.some(child => isElement(child, 'hr'))) {
    // eslint-disable-next-line no-param-reassign
    node.children = node.children.filter(child => !isElement(child, 'hr'));
    parent.children.splice((index + 1), 0, hastscript('hr'));
    if (node.children.length === 0) {
      parent.children.splice(index, 1);
      return index;
    }
    return index + 1;
  }
  return utilVisit.CONTINUE;
});
```

When I replace the `<b>` tag with a `<div>` and return the same index, I intend for the `<b>` tag's children to be ignored and for the loop to continue with `<div>` tag and its children. However, because I didn't return `utilVisit.SKIP`, the visitor is called with the `<b>` tag's children. It then ends up mutating the parent's child array (thanks to the `<p>` tag handling), but that mutation doesn't get applied to the `<div>`, and by the time the visitor eventually handles the `<div>` tag and its children, the condition no longer applies to the `<p>` tag inside the `<div>`.

I hope that made sense.

I don't want to simply return SKIP in this case, because after replacing the current node, I want to visit its replacement and the replacement's children.

Proposed fix: change the visit-children condition from "visit children unless result was SKIP" to "visit children unless result was SKIP or an integer less than or equal to the current index"

**Comment by wooorm** [comment]
Thanks for the detailed issue! It makes sense, it’s just a bit confusing to wrap my head around even though I wrote the utilities 😅

For a solution is see three ways to go:

* Don’t replace the `b` with `div`, but do `node.tagName = 'div'` (potentially also clean the `properties`)
* Your proposal, but I can see how other people would want the current situation
* Allow combined options, e.g., something like returning `[visit.SKIP, index]` from the visitor

**Comment by inklesspen** [comment]
of those three options, I prefer the third.

**Comment by wooorm** [comment]
I guess it doesn’t make sense to allow CONTINUE and EXIT in that list though 🤔
